version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hoc_cung_ban
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
  db:
    image: mysql:8.0.30
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=hoc_cung_ban
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: